workflows:
  build-android:
    name: React Native Android Build
    environment:
      node: 16
      java: 11
    scripts:
      - name: Install dependencies with legacy-peer-deps
        script: |
          npm install --legacy-peer-deps
          if [ -d "android" ]; then
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
          else
            echo "No android folder found! This may not be a React Native project."
            exit 1
          fi
    artifacts:
      - android/app/build/outputs/**/*.apkapk